import type { NextPage } from 'next'
import Head from 'next/head'
import { adberbList } from '../public/data/adberbList'
import { conteList } from '../public/data/conteList'
import { endList } from '../public/data/endList'
import { fableList } from '../public/data/fableList'
import { femaleList } from '../public/data/femaleList'
import { fourthParagraphList } from '../public/data/fourthParagraphList'
import { itemList } from '../public/data/itemList'
import { livreList } from '../public/data/livreList'
import { maleList } from '../public/data/maleList'
import { musiqueListe } from '../public/data/musiqueListe'
import { styleMusiqueList } from '../public/data/styleMusiqueList'
import { subjectList } from '../public/data/subjectList'
import { tableauList } from '../public/data/tableauList'
import { thirdParagraphPart1 } from '../public/data/thirdParagraphPart1'
import { thirdParagraphPart2 } from '../public/data/thirdParagraphPart2'

export default function Index() {

  let start: string[] = []
  const begin = subjectList[random(subjectList.length)];
  if (begin === subjectList[0]) {
    start = femaleList;
  } else {
    start = maleList;
  }
  const firstParagraph = begin + " " + start[random(start.length)] + " " + endList[random(endList.length)] + "."
  const item = itemList[random(itemList.length)];
  let secondParagraph = "C'est " + adberbList[random(adberbList.length)] + " " + item + ": ";
  if (item === "du Tableau") {
    secondParagraph = secondParagraph + tableauList[random(tableauList.length)] + "."
  } else if (item === "de la Fable") {
    secondParagraph = secondParagraph + fableList[random(fableList.length)] + " De Jean de La Fontaine."
  } else if (item === "du Livre") {
    secondParagraph = secondParagraph + livreList[random(livreList.length)] + "."
  } else if (item === "du Conte") {
    secondParagraph = secondParagraph + conteList[random(conteList.length)] + "."
  }

  const thirdParagraph = thirdParagraphPart1[random(thirdParagraphPart1.length)] + " " + thirdParagraphPart2[random(thirdParagraphPart2.length)] +"."
  const fourthParagraph = "Comme le réalisateur le souligne: '" + fourthParagraphList[random(fourthParagraphList.length)] + "'"
  const fifthParagraph = "La musique est une approche plus " + styleMusiqueList[random(styleMusiqueList.length)] + " de "
    + musiqueListe[random(musiqueListe.length)] + "."


  const porps = {
    headtitre: "Review generator",
    titre: "Générateur de critique évolué pour te la péter en société.",
    finexcuse: ", donc je ne peux pas t'augmenter.",
    promesse: "La prochaine fois c'est promis...",
    label: "Raconte-toi là encore => ",
    btntext: "ICI",
    conclusion: "Tu n'as pas vu le film, mais tu veux donner ton avis...",
    signature: "By Maysk@"

  }
  return (
    <div className="container-xl">
      <Head>
        <title>{porps.headtitre}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <br />
        <h3 className="text-center">{porps.titre}</h3>
        <h6 className='text-center text-muted'>{porps.conclusion}</h6>

        <div className="row">
          <div className="col">
          </div>
          <div className="col-10">
            <hr />
            <form action="/" method="GET">
              <p className='text fs-6'>{firstParagraph}</p>
              <p className='text fs-6'>{thirdParagraph}</p>
              <p className='text fs-6'>{secondParagraph}</p>
              <p className='text fs-6'>{fifthParagraph}</p>
              <p className='text fs-6 fst-italic'>{fourthParagraph}</p>
              <hr />
              <label>{porps.label}<button type="submit" className="btn btn-success">{porps.btntext}</button></label>
            </form>
            <hr />
          </div>
          <div className="col"></div>
        </div>
      </main>
      <footer>
        <br />
        <br />
        <p className='text-end text-muted'>{porps.signature}</p>
      </footer>
    </div>
  )
}


function random(max: number) {
  return Math.floor(Math.random() * Math.floor(max));
}